name: Run Tests

on: [push]

jobs:
  code-checks:
    strategy:
      matrix:
        tools:
          - command: "mypy ./basekit_driver --non-interactive"
          - command: "mypy ./basekit_launch --non-interactive"
          - command: "mypy ./basekit_ui --non-interactive"
          - command: "pylint ./basekit_driver/basekit_driver"
          - command: "pylint ./basekit_ui/basekit_ui"
          - command: "ruff check ./basekit_driver"
          - command: "ruff check ./basekit_launch"
          - command: "ruff check ./basekit_ui"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: install dependencies
        run: pip install -r requirements-dev.txt
      - name: ${{ matrix.tools.command }}
        run: ${{ matrix.tools.command }}
