name: Run Tests

on: [push]

jobs:
  code-checks:
    strategy:
      matrix:
        tools:
          - command: "mypy ./devkit_driver --non-interactive"
          - command: "mypy ./devkit_launch --non-interactive"
          - command: "mypy ./devkit_ui --non-interactive"
          - command: "pylint ./devkit_driver/devkit_driver"
          - command: "pylint ./devkit_ui/devkit_ui"
          - command: "ruff check ./devkit_driver"
          - command: "ruff check ./devkit_launch"
          - command: "ruff check ./devkit_ui"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: install dependencies
        run: pip install -r requirements-dev.txt
      - name: ${{ matrix.tools.command }}
        run: ${{ matrix.tools.command }}
